[object]
id = "SpawnPoint"
name = "Spawn Point"
category = ["Marker"]
aspects = []
player_controllable = false

[physics]
mode = "static"
size = [12, 12]
solid = false
overlap_detection = false

[visual]
color = [0, 100, 255]

[properties]
team = 1
