[game]
id      = "europa-fighters"
name    = "Europa Fighters"
version = "0.1.0"

[window]
width  = 1280
height = 720

[ui]
debugger = false  # set true to enable RmlUi's inspector overlay

[startup]
script = "scripts/main.lua"

[packages]
load = [
    "packages/europa-fighters/base"
]
