[material]
id   = "Vacuum"
name = "Vacuum"

[physics]
state    = "none"
density  = 0
friction = 0.0
hardness = 0

[visual]
color        = [5, 8, 18]
transparency = 1.0

[behavior]
gravity = false

[temperature]
conducts_heat = false
