[object]
id                 = "SpreadShot"
name               = "Spread Shot"
category           = ["Projectile"]
player_controllable = false

[physics]
mode              = "dynamic"
mass              = 1
max_fall_speed    = 2000.0
size              = [3, 3]
rotation          = false
solid             = false
overlap_detection = true
step_up           = 0

[visual]
color = [180, 255, 140]

[properties]
damage         = 12.0
speed          = 480.0
lifetime_ticks = 80.0
owner_id       = 0.0
